# Alle Prüfungen nacheinander. Aufruf im Ordner pruefstand:  python alle_tests.py
import re, subprocess, sys
TESTS = ['final', 'rechner', 'einkauf', 'bestellungen', 'start', 'produktion', 'pad', 'auftrag', 'suche_alles', 'ferien', 'hoco_fenster', 'typen', 'dokumente', 'farben', 'nutzer', 'pad_teile', 'betrachter_pdf', 'cachse', 'gravur', 'dxf', 'bestellposition', 'einstellungen', 'anmeldung', 'ziehen3', 'kopieren', 'rueckgaengig', 'extern', 'paddash', 'escape', 'heute_backup', 'taste_h', 'bestzeit', 'acht', 'startruhe', 'padtext', 'padstart', 'padweg', 'suche_reihe', 'woche_platz', 'sieben', 'zurueck2022', 'mailbilder', 'blatt_schrift', 'heute_linie', 'geburtstag', 'merken', 'geraetzurueck', 'vier2', 'ohnekamera', 'pin', 'offen', 'effekte', 'tag_platz', 'doppelklick', 'ansehen_auftrag', 'typfilter', 'bestellungen_neu', 'schieber_frei', 'menge_offen', 'excel_ansicht', 'dokpool', 'notiz_material', 'zuschnitt', 'materialplatz', 'enter_eindeutig', 'vorschau_laenge', 'auftragswechsel', 'farben_kraeftig', 'randblaettern', 'eb_ordner', 'hoco_typen', 'stueck_tag', 'schnitt_arbeitstage', 'wischen_finger', 'padfett', 'padwetter', 'padskizze_gross', 'zeichnung_hoco', 'pad_typen_raster', 'padskizze', 'auftrag_layout', 'bestellungen_namen', 'padskizze_text', 'pad_neuladen', 'sicherung', 'rueckgaengig_ueberall', 'pad_handy', 'loeschen_einmal', 'bestellmail_fenster', 'notizbuch', 'notizbuch_klein', 'notizbuch_tabelle', 'profilbilder', 'andere_nutzer', 'home_icon', 'materialausgabe', 'abruf_siegel', 'stueckzeit', 'planwand_symbole', 'balken_schrift', 'naechster_ruesten', 'andere_nie_abmelden', 'fassung_neu', 'zeichnung_entfernen', 'stuendlich_neuladen', 'wochenlinie', 'dok_entfernen', 'pad_drucken', 'kopf_oben', 'pool_drucken', 'padwetter_fenster', 'zeichnung_pfad', 'balken_hervorheben', 'eigenes_passwort', 'ferien_jeder', 'wiederherstellen', 'planwand_fluessig', 'abruf_mehrzeilig', 'planwand_nur_admin', 'google_knopf']
gut = 0
for t in TESTS:
    r = subprocess.run([sys.executable, t + ".py"], capture_output=True, text=True, timeout=400)
    # Auch Zeilen wie "Fehler Pad: …" zählen, nicht nur "Fehler: …"
    zeilen = [z for z in (r.stdout + r.stderr).splitlines() if re.search(r"Fehler( \w+)?:", z) or "Error" in z]
    ok = r.returncode == 0 and not any("Error" in z for z in zeilen) and all(re.search(r"Fehler( \w+)?: keine", z) for z in zeilen if re.search(r"Fehler( \w+)?:", z))
    gut += ok
    print(("OK    " if ok else "FEHLER") + "  " + t + ("" if ok else "  ->  " + " | ".join(zeilen[-2:])))
print("\n%d von %d Prüfungen ohne Fehler" % (gut, len(TESTS)))
